# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/jacoboffersen/Repos/lab4/src/RGB_Matrix_constrains.xdc

# Block Designs: bd/LED_RAM/LED_RAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_RAM || ORIG_REF_NAME==LED_RAM} -quiet] -quiet

# IP: bd/LED_RAM/ip/LED_RAM_processing_system7_0_0/LED_RAM_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_RAM_processing_system7_0_0 || ORIG_REF_NAME==LED_RAM_processing_system7_0_0} -quiet] -quiet

# IP: bd/LED_RAM/ip/LED_RAM_blk_mem_gen_0_0/LED_RAM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_RAM_blk_mem_gen_0_0 || ORIG_REF_NAME==LED_RAM_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/LED_RAM/ip/LED_RAM_axi_bram_ctrl_0_0/LED_RAM_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_RAM_axi_bram_ctrl_0_0 || ORIG_REF_NAME==LED_RAM_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/LED_RAM/ip/LED_RAM_axi_smc_0/LED_RAM_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_RAM_axi_smc_0 || ORIG_REF_NAME==LED_RAM_axi_smc_0} -quiet] -quiet

# IP: bd/LED_RAM/ip/LED_RAM_rst_ps7_0_100M_0/LED_RAM_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_RAM_rst_ps7_0_100M_0 || ORIG_REF_NAME==LED_RAM_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/LED_RAM/LED_RAM_ooc.xdc
